apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api.fullname" . }}-manager
  labels:
    cluster.x-k8s.io/provider: cluster-api
    clusterctl.cluster.x-k8s.io: ""
  {{- include "cluster-api.labels" . | nindent 4 }}
