# Cluster parameters
workersNumber: 2

clusterNetwork:
  pods:
    cidrBlocks:
    - "10.244.0.0/16"
  services:
    cidrBlocks:
    - "10.96.0.0/12"

# AWS cluster parameters
vpcID: ""
region: ""
sshKeyName: ""
publicIP: false
subnets:
  - id: ""
    availabilityZone: ""
bastion:
  enabled: false
  disableIngressRules: false
  allowedCIDRBlocks: []
  instanceType: t2.micro
  ami: ""
# AWS machines parameters
amiID: ""
iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
instanceType: ""
securityGroupIDs: []

# K0smotron parameters
k0smotron:
  service:
    type: LoadBalancer
    apiPort: 6443
    konnectivityPort: 8132

# K0s parameters
k0s:
  version: v1.30.2+k0s.0
