apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api-provider-aws.fullname" . }}-controller-manager
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  {{- include "cluster-api-provider-aws.labels" . | nindent 4 }}
  {{- if .Values.awsControllerIamRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.awsControllerIamRole }}
  {{- end }}
