# permissions for end users to edit deployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hmc
    app.kubernetes.io/managed-by: kustomize
  name: deployment-editor-role
rules:
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments/status
  verbs:
  - get
