# permissions for end users to view managements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hmc
    app.kubernetes.io/managed-by: kustomize
  name: management-viewer-role
rules:
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - managements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - managements/status
  verbs:
  - get
