resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_service.yaml
# For each CRD, "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the Project itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- awsprovider_editor_role.yaml
- awsprovider_viewer_role.yaml
- management_editor_role.yaml
- management_viewer_role.yaml
- deployment_editor_role.yaml
- deployment_viewer_role.yaml
- template_editor_role.yaml
- template_viewer_role.yaml

