---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsprovider
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsprovider/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - awsprovider/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - managements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - hmc.mirantis.com
  resources:
  - templates/status
  verbs:
  - get
  - patch
  - update
