# permissions for end users to edit templates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hmc
    app.kubernetes.io/managed-by: kustomize
  name: template-editor-role
rules:
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hmc.mirantis.com.hmc.mirantis.com
  resources:
  - templates/status
  verbs:
  - get
