apiVersion: hmc.mirantis.com/v1alpha1
kind: Management
metadata:
  labels:
    app.kubernetes.io/name: hmc
    app.kubernetes.io/managed-by: kustomize
  name: management-sample
spec:
  # TODO(user): Add fields here
