apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hmc-templates
  namespace: hmc-system
spec:
  interval: 10m0s
  type: oci
  url: oci://hmc-local-registry:5000/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: hmc
  namespace: hmc-system
spec:
  chart: hmc
  interval: 10m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: hmc-templates
  version: VERSION
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hmc
  namespace: hmc-system
spec:
  chartRef:
    kind: HelmChart
    name: hmc
    namespace: hmc-system
  interval: 10m0s
  releaseName: hmc
