apiVersion: hmc.mirantis.com/v1alpha1
kind: Deployment
metadata:
  name: aws-dev
  namespace: ${NAMESPACE}
spec:
  template: aws-standalone-cp
  config:
    region: us-east-2
    publicIP: true
    controlPlaneNumber: 1
    workersNumber: 1
    controlPlane:
      instanceType: t3.small
    worker:
      instanceType: t3.small
