apiVersion: hmc.mirantis.com/v1alpha1
kind: Management
metadata:
  name: hmc
spec:
  providers:
    - template: cluster-api-provider-aws
      config:
        credentialsSecretName: aws-credentials
    - template: k0smotron
