apiVersion: hmc.mirantis.com/v1alpha1
kind: ProviderTemplate
metadata:
  name: projectsveltos
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartName: projectsveltos
    chartVersion: 0.38.2
