name: Build and Test

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - "*"
    paths-ignore:
      - 'config/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - release-*
    tags:
      - "*"
    paths-ignore:
      - 'config/**'
      - '**.md'

env:
  GO_VERSION: '1.22'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check go mod
        run: go mod tidy && git diff --exit-code
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m0s
      - name: Unit tests
        run: |
          make test
      - name: Build
        run: | 
          make build
      - name: Image build
        run: |
          make docker-build
